apiVersion: dbs.hsdp.crossplane.io/v1alpha1
kind: SqsSubscriber
metadata:
  annotations:
    meta.upbound.io/example-id: dbs/v1alpha1/sqssubscriber
  labels:
    testing.upbound.io/example-name: my-subscriber
  name: my-subscriber
spec:
  forProvider:
    deliveryDelaySeconds: 0
    description: My subscriber
    messageRetentionPeriodSeconds: 0
    nameInfix: my-subscriber
    queueType: Standard
    receiveWaitTimeSeconds: 0
    serverSideEncryption: true
