/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Application) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Client) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EmailTemplate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Group) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Organization) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PasswordPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Proposition) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Role) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RoleSharingPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Service) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}
