// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RoleSharingPolicyInitParameters struct {

	// The purpose of this role sharing policy mapping
	Purpose *string `json:"purpose,omitempty" tf:"purpose,omitempty"`

	// The policy to use
	// Sharing of a role with a tenant organization can be in one of the following modes:
	SharingPolicy *string `json:"sharingPolicy,omitempty" tf:"sharing_policy,omitempty"`
}

type RoleSharingPolicyObservation struct {

	// The GUID of the role sharing policy (also known as internalId at the API level)
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The purpose of this role sharing policy mapping
	Purpose *string `json:"purpose,omitempty" tf:"purpose,omitempty"`

	// The ID of the role to share
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// The role name
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`

	// The policy to use
	// Sharing of a role with a tenant organization can be in one of the following modes:
	SharingPolicy *string `json:"sharingPolicy,omitempty" tf:"sharing_policy,omitempty"`

	// The source organization ID
	SourceOrganizationID *string `json:"sourceOrganizationId,omitempty" tf:"source_organization_id,omitempty"`

	// The target organization UUID to apply this policy for. This can either be a root IAM Org or a subOrg in an existing hierarchy
	TargetOrganizationID *string `json:"targetOrganizationId,omitempty" tf:"target_organization_id,omitempty"`
}

type RoleSharingPolicyParameters struct {

	// Reference to a Organization to populate targetOrganizationId.
	// +kubebuilder:validation:Optional
	OrganizationRef *v1.Reference `json:"organizationRef,omitempty" tf:"-"`

	// The purpose of this role sharing policy mapping
	// +kubebuilder:validation:Optional
	Purpose *string `json:"purpose,omitempty" tf:"purpose,omitempty"`

	// The ID of the role to share
	// +crossplane:generate:reference:type=Role
	// +crossplane:generate:reference:refFieldName=RoleRef
	// +kubebuilder:validation:Optional
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// Selector for a Role to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDSelector *v1.Selector `json:"roleIdSelector,omitempty" tf:"-"`

	// Reference to a Role to populate roleId.
	// +kubebuilder:validation:Optional
	RoleRef *v1.Reference `json:"roleRef,omitempty" tf:"-"`

	// The policy to use
	// Sharing of a role with a tenant organization can be in one of the following modes:
	// +kubebuilder:validation:Optional
	SharingPolicy *string `json:"sharingPolicy,omitempty" tf:"sharing_policy,omitempty"`

	// The target organization UUID to apply this policy for. This can either be a root IAM Org or a subOrg in an existing hierarchy
	// +crossplane:generate:reference:type=Organization
	// +crossplane:generate:reference:refFieldName=OrganizationRef
	// +kubebuilder:validation:Optional
	TargetOrganizationID *string `json:"targetOrganizationId,omitempty" tf:"target_organization_id,omitempty"`

	// Selector for a Organization to populate targetOrganizationId.
	// +kubebuilder:validation:Optional
	TargetOrganizationIDSelector *v1.Selector `json:"targetOrganizationIdSelector,omitempty" tf:"-"`
}

// RoleSharingPolicySpec defines the desired state of RoleSharingPolicy
type RoleSharingPolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RoleSharingPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RoleSharingPolicyInitParameters `json:"initProvider,omitempty"`
}

// RoleSharingPolicyStatus defines the observed state of RoleSharingPolicy.
type RoleSharingPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RoleSharingPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// RoleSharingPolicy is the Schema for the RoleSharingPolicys API. Manages HSDP IAM Role sharing policy resources
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,hsdp}
type RoleSharingPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sharingPolicy) || (has(self.initProvider) && has(self.initProvider.sharingPolicy))",message="spec.forProvider.sharingPolicy is a required parameter"
	Spec   RoleSharingPolicySpec   `json:"spec"`
	Status RoleSharingPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoleSharingPolicyList contains a list of RoleSharingPolicys
type RoleSharingPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RoleSharingPolicy `json:"items"`
}

// Repository type metadata.
var (
	RoleSharingPolicy_Kind             = "RoleSharingPolicy"
	RoleSharingPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RoleSharingPolicy_Kind}.String()
	RoleSharingPolicy_KindAPIVersion   = RoleSharingPolicy_Kind + "." + CRDGroupVersion.String()
	RoleSharingPolicy_GroupVersionKind = CRDGroupVersion.WithKind(RoleSharingPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&RoleSharingPolicy{}, &RoleSharingPolicyList{})
}
