/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ObjectStoreObservation struct {
	AccessType *string `json:"accessType,omitempty" tf:"access_type,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ObjectStoreParameters struct {

	// +kubebuilder:validation:Required
	ConfigURL *string `json:"configUrl" tf:"config_url,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	ForceDelete *bool `json:"forceDelete,omitempty" tf:"force_delete,omitempty"`

	// +crossplane:generate:reference:type=github.com/philips-software/provider-hsdp/apis/iam/v1alpha1.Organization
	// +crossplane:generate:reference:refFieldName=OrganizationRef
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Selector for a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationIDSelector *v1.Selector `json:"organizationIdSelector,omitempty" tf:"-"`

	// Reference to a Organization in iam to populate organizationId.
	// +kubebuilder:validation:Optional
	OrganizationRef *v1.Reference `json:"organizationRef,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	S3CredsAccess []S3CredsAccessParameters `json:"s3credsAccess,omitempty" tf:"s3creds_access,omitempty"`

	// +kubebuilder:validation:Optional
	StaticAccess []StaticAccessParameters `json:"staticAccess,omitempty" tf:"static_access,omitempty"`
}

type S3CredsAccessObservation struct {
}

type S3CredsAccessParameters struct {

	// +kubebuilder:validation:Required
	BucketName *string `json:"bucketName" tf:"bucket_name,omitempty"`

	// +kubebuilder:validation:Required
	Endpoint *string `json:"endpoint" tf:"endpoint,omitempty"`

	// +kubebuilder:validation:Required
	FolderPath *string `json:"folderPath" tf:"folder_path,omitempty"`

	// +kubebuilder:validation:Required
	ProductKeySecretRef v1.SecretKeySelector `json:"productKeySecretRef" tf:"-"`

	// +kubebuilder:validation:Optional
	ServiceAccount []ServiceAccountParameters `json:"serviceAccount,omitempty" tf:"service_account,omitempty"`
}

type ServiceAccountObservation struct {
}

type ServiceAccountParameters struct {

	// +kubebuilder:validation:Required
	AccessTokenEndpoint *string `json:"accessTokenEndpoint" tf:"access_token_endpoint,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Required
	PrivateKeySecretRef v1.SecretKeySelector `json:"privateKeySecretRef" tf:"-"`

	// +kubebuilder:validation:Required
	ServiceID *string `json:"serviceId" tf:"service_id,omitempty"`

	// +kubebuilder:validation:Required
	TokenEndpoint *string `json:"tokenEndpoint" tf:"token_endpoint,omitempty"`
}

type StaticAccessObservation struct {
}

type StaticAccessParameters struct {

	// +kubebuilder:validation:Required
	AccessKeySecretRef v1.SecretKeySelector `json:"accessKeySecretRef" tf:"-"`

	// +kubebuilder:validation:Required
	BucketName *string `json:"bucketName" tf:"bucket_name,omitempty"`

	// +kubebuilder:validation:Required
	Endpoint *string `json:"endpoint" tf:"endpoint,omitempty"`

	// +kubebuilder:validation:Required
	SecretKeySecretRef v1.SecretKeySelector `json:"secretKeySecretRef" tf:"-"`
}

// ObjectStoreSpec defines the desired state of ObjectStore
type ObjectStoreSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ObjectStoreParameters `json:"forProvider"`
}

// ObjectStoreStatus defines the observed state of ObjectStore.
type ObjectStoreStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ObjectStoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ObjectStore is the Schema for the ObjectStores API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,hsdp}
type ObjectStore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ObjectStoreSpec   `json:"spec"`
	Status            ObjectStoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ObjectStoreList contains a list of ObjectStores
type ObjectStoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ObjectStore `json:"items"`
}

// Repository type metadata.
var (
	ObjectStore_Kind             = "ObjectStore"
	ObjectStore_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ObjectStore_Kind}.String()
	ObjectStore_KindAPIVersion   = ObjectStore_Kind + "." + CRDGroupVersion.String()
	ObjectStore_GroupVersionKind = CRDGroupVersion.WithKind(ObjectStore_Kind)
)

func init() {
	SchemeBuilder.Register(&ObjectStore{}, &ObjectStoreList{})
}
