apiVersion: iam.hsdp.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/application
  labels:
    testing.upbound.io/example-name: testapp
  name: testapp
spec:
  forProvider:
    description: Test application
    name: TESTAPP
    propositionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: testprop
