apiVersion: iam.hsdp.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/client
  labels:
    testing.upbound.io/example-name: testclient
  name: testclient
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: testtapp
    clientId: testclient
    defaultScopes:
    - cn
    - introspect
    description: Test client
    globalReferenceId: some-ref-here
    name: TESTCLIENT
    passwordSecretRef:
      key: attribute.result
      name: example-password
      namespace: upbound-system
    redirectionUris:
    - https://foo.bar/auth
    - https://testapp.cloud.pcftest.com/auth
    responseTypes:
    - code
    - code id_token
    scopes:
    - cn
    - introspect
    - email
    - profile
    type: Public
