apiVersion: iam.hsdp.crossplane.io/v1alpha1
kind: EmailTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/emailtemplate
  labels:
    testing.upbound.io/example-name: password_changed
  name: password-changed
spec:
  forProvider:
    format: HTML
    managingOrganizationSelector:
      matchLabels:
        testing.upbound.io/example-name: hsdp_iam_org
    message: |
      Dear {{user.givenName}},

      Your password was recently changed. If this was not initiated
      by you please contact support immediately.

      Kind regards,
      IAM Team
    subject: Your IAM account password was changed
    type: PASSWORD_CHANGED
