apiVersion: iam.hsdp.crossplane.io/v1alpha1
kind: PasswordPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/passwordpolicy
  labels:
    testing.upbound.io/example-name: mypolicy
  name: mypolicy
spec:
  forProvider:
    complexity:
    - maxLength: 32
      minLength: 8
      minLowercase: 1
      minNumerics: 1
      minSpecialChars: 1
      minUppercase: 1
    expiryPeriodInDays: 180
    historyCount: 5
    managingOrganizationSelector:
      matchLabels:
        testing.upbound.io/example-name: hsdp_iam_org
