//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqsSubscriber) DeepCopyInto(out *SqsSubscriber) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqsSubscriber.
func (in *SqsSubscriber) DeepCopy() *SqsSubscriber {
	if in == nil {
		return nil
	}
	out := new(SqsSubscriber)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SqsSubscriber) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqsSubscriberInitParameters) DeepCopyInto(out *SqsSubscriberInitParameters) {
	*out = *in
	if in.DeliveryDelaySeconds != nil {
		in, out := &in.DeliveryDelaySeconds, &out.DeliveryDelaySeconds
		*out = new(int64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.MessageRetentionPeriodSeconds != nil {
		in, out := &in.MessageRetentionPeriodSeconds, &out.MessageRetentionPeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.NameInfix != nil {
		in, out := &in.NameInfix, &out.NameInfix
		*out = new(string)
		**out = **in
	}
	if in.QueueType != nil {
		in, out := &in.QueueType, &out.QueueType
		*out = new(string)
		**out = **in
	}
	if in.ReceiveWaitTimeSeconds != nil {
		in, out := &in.ReceiveWaitTimeSeconds, &out.ReceiveWaitTimeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ServerSideEncryption != nil {
		in, out := &in.ServerSideEncryption, &out.ServerSideEncryption
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqsSubscriberInitParameters.
func (in *SqsSubscriberInitParameters) DeepCopy() *SqsSubscriberInitParameters {
	if in == nil {
		return nil
	}
	out := new(SqsSubscriberInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqsSubscriberList) DeepCopyInto(out *SqsSubscriberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SqsSubscriber, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqsSubscriberList.
func (in *SqsSubscriberList) DeepCopy() *SqsSubscriberList {
	if in == nil {
		return nil
	}
	out := new(SqsSubscriberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SqsSubscriberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqsSubscriberObservation) DeepCopyInto(out *SqsSubscriberObservation) {
	*out = *in
	if in.DeliveryDelaySeconds != nil {
		in, out := &in.DeliveryDelaySeconds, &out.DeliveryDelaySeconds
		*out = new(int64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MessageRetentionPeriodSeconds != nil {
		in, out := &in.MessageRetentionPeriodSeconds, &out.MessageRetentionPeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameInfix != nil {
		in, out := &in.NameInfix, &out.NameInfix
		*out = new(string)
		**out = **in
	}
	if in.QueueName != nil {
		in, out := &in.QueueName, &out.QueueName
		*out = new(string)
		**out = **in
	}
	if in.QueueType != nil {
		in, out := &in.QueueType, &out.QueueType
		*out = new(string)
		**out = **in
	}
	if in.ReceiveWaitTimeSeconds != nil {
		in, out := &in.ReceiveWaitTimeSeconds, &out.ReceiveWaitTimeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ServerSideEncryption != nil {
		in, out := &in.ServerSideEncryption, &out.ServerSideEncryption
		*out = new(bool)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqsSubscriberObservation.
func (in *SqsSubscriberObservation) DeepCopy() *SqsSubscriberObservation {
	if in == nil {
		return nil
	}
	out := new(SqsSubscriberObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqsSubscriberParameters) DeepCopyInto(out *SqsSubscriberParameters) {
	*out = *in
	if in.DeliveryDelaySeconds != nil {
		in, out := &in.DeliveryDelaySeconds, &out.DeliveryDelaySeconds
		*out = new(int64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.MessageRetentionPeriodSeconds != nil {
		in, out := &in.MessageRetentionPeriodSeconds, &out.MessageRetentionPeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.NameInfix != nil {
		in, out := &in.NameInfix, &out.NameInfix
		*out = new(string)
		**out = **in
	}
	if in.QueueType != nil {
		in, out := &in.QueueType, &out.QueueType
		*out = new(string)
		**out = **in
	}
	if in.ReceiveWaitTimeSeconds != nil {
		in, out := &in.ReceiveWaitTimeSeconds, &out.ReceiveWaitTimeSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ServerSideEncryption != nil {
		in, out := &in.ServerSideEncryption, &out.ServerSideEncryption
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqsSubscriberParameters.
func (in *SqsSubscriberParameters) DeepCopy() *SqsSubscriberParameters {
	if in == nil {
		return nil
	}
	out := new(SqsSubscriberParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqsSubscriberSpec) DeepCopyInto(out *SqsSubscriberSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqsSubscriberSpec.
func (in *SqsSubscriberSpec) DeepCopy() *SqsSubscriberSpec {
	if in == nil {
		return nil
	}
	out := new(SqsSubscriberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqsSubscriberStatus) DeepCopyInto(out *SqsSubscriberStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqsSubscriberStatus.
func (in *SqsSubscriberStatus) DeepCopy() *SqsSubscriberStatus {
	if in == nil {
		return nil
	}
	out := new(SqsSubscriberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscription) DeepCopyInto(out *TopicSubscription) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscription.
func (in *TopicSubscription) DeepCopy() *TopicSubscription {
	if in == nil {
		return nil
	}
	out := new(TopicSubscription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopicSubscription) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionInitParameters) DeepCopyInto(out *TopicSubscriptionInitParameters) {
	*out = *in
	if in.DataType != nil {
		in, out := &in.DataType, &out.DataType
		*out = new(string)
		**out = **in
	}
	if in.DeliverDataOnly != nil {
		in, out := &in.DeliverDataOnly, &out.DeliverDataOnly
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.KinesisStreamPartitionKey != nil {
		in, out := &in.KinesisStreamPartitionKey, &out.KinesisStreamPartitionKey
		*out = new(string)
		**out = **in
	}
	if in.NameInfix != nil {
		in, out := &in.NameInfix, &out.NameInfix
		*out = new(string)
		**out = **in
	}
	if in.SubscriberID != nil {
		in, out := &in.SubscriberID, &out.SubscriberID
		*out = new(string)
		**out = **in
	}
	if in.SubscriberIDSelector != nil {
		in, out := &in.SubscriberIDSelector, &out.SubscriberIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SubscriberRef != nil {
		in, out := &in.SubscriberRef, &out.SubscriberRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionInitParameters.
func (in *TopicSubscriptionInitParameters) DeepCopy() *TopicSubscriptionInitParameters {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionList) DeepCopyInto(out *TopicSubscriptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TopicSubscription, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionList.
func (in *TopicSubscriptionList) DeepCopy() *TopicSubscriptionList {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopicSubscriptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionObservation) DeepCopyInto(out *TopicSubscriptionObservation) {
	*out = *in
	if in.DataType != nil {
		in, out := &in.DataType, &out.DataType
		*out = new(string)
		**out = **in
	}
	if in.DeliverDataOnly != nil {
		in, out := &in.DeliverDataOnly, &out.DeliverDataOnly
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.KinesisStreamPartitionKey != nil {
		in, out := &in.KinesisStreamPartitionKey, &out.KinesisStreamPartitionKey
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameInfix != nil {
		in, out := &in.NameInfix, &out.NameInfix
		*out = new(string)
		**out = **in
	}
	if in.RuleName != nil {
		in, out := &in.RuleName, &out.RuleName
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.SubscriberID != nil {
		in, out := &in.SubscriberID, &out.SubscriberID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionObservation.
func (in *TopicSubscriptionObservation) DeepCopy() *TopicSubscriptionObservation {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionParameters) DeepCopyInto(out *TopicSubscriptionParameters) {
	*out = *in
	if in.DataType != nil {
		in, out := &in.DataType, &out.DataType
		*out = new(string)
		**out = **in
	}
	if in.DeliverDataOnly != nil {
		in, out := &in.DeliverDataOnly, &out.DeliverDataOnly
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.KinesisStreamPartitionKey != nil {
		in, out := &in.KinesisStreamPartitionKey, &out.KinesisStreamPartitionKey
		*out = new(string)
		**out = **in
	}
	if in.NameInfix != nil {
		in, out := &in.NameInfix, &out.NameInfix
		*out = new(string)
		**out = **in
	}
	if in.SubscriberID != nil {
		in, out := &in.SubscriberID, &out.SubscriberID
		*out = new(string)
		**out = **in
	}
	if in.SubscriberIDSelector != nil {
		in, out := &in.SubscriberIDSelector, &out.SubscriberIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SubscriberRef != nil {
		in, out := &in.SubscriberRef, &out.SubscriberRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionParameters.
func (in *TopicSubscriptionParameters) DeepCopy() *TopicSubscriptionParameters {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionSpec) DeepCopyInto(out *TopicSubscriptionSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionSpec.
func (in *TopicSubscriptionSpec) DeepCopy() *TopicSubscriptionSpec {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicSubscriptionStatus) DeepCopyInto(out *TopicSubscriptionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicSubscriptionStatus.
func (in *TopicSubscriptionStatus) DeepCopy() *TopicSubscriptionStatus {
	if in == nil {
		return nil
	}
	out := new(TopicSubscriptionStatus)
	in.DeepCopyInto(out)
	return out
}
