apiVersion: tenant.hsdp.crossplane.io/v1alpha1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: tenant/v1alpha1/key
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    environment: prod
    expiration: "2025-12-31T23:59:59Z"
    organization: my-organization
    project: my-project
    region: us-east
    salt: static-salt-value
    scopes:
    - scope1
    - scope2
    signingKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
